<!DOCTYPE HTML><html><head>
   <meta charset="utf-8">
   	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<link rel="icon" href="https://jscdn.com.cn/highcharts/images/favicon.ico">

   <meta name="description" content="">
   <title>asd</title>
   
   <style></style>
   
</head><body>
<!--
*************************************************************************
    Generated by JShare at 2021-02-06 16:40:01
    From: https://jshare.com.cn/public/O0GnuL
*************************************************************************
-->
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		<title>音乐播放器</title>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css">
		<style type="text/css">
			html, body, .aplayer{
				margin: 0;
				padding: 0;
			}
		</style>
		<script src="https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/meting@2/dist/Meting.min.js"></script>
	</head>
	<body>
		<meting-js
				   server="netease"
				   type="playlist"
				   id="6602011046"
				   list-max-height="95px"
				   >
		</meting-js>
	</body>
</html>

</body></html>
